### ISSUE TITLE
Add support for `AsyncBufRead`

### ISSUE THREAD

**Issue by fogti** [stjepang/async-dup#1]
It would be nice if this crate would support `AsyncBufRead` besides `AsyncRead` and `AsyncWrite`, which would make it even more useful than `ReadHalf + WriteHalf` from `futures_util`...

**Comment by ghost** [comment]
The problem with `AsyncBufRead` is that `poll_fill_buf()` returns a reference borrowing `self`, so this doesn't work:

```
error[E0515]: cannot return value referencing function parameter `self`
   --> src/lib.rs:176:9
    |
176 |         Pin::new(&mut &*self.0).poll_fill_buf(cx)
    |         ^^^^^^^^^^^^^^^^----^^^^^^^^^^^^^^^^^^^^^
    |         |               |
    |         |               `self` is borrowed here
    |         returns a value referencing data owned by the current function
```

I don't see a way around this, unfortunately :(

**Comment by fogti** [comment]
Ah, ok.

**Comment by fogti** [comment]
The issue I want to work around is: rust-lang/futures-rs#2174
