### ISSUE TITLE
`async_dup::MutexGuard` is !Send in `1.2.3`

### ISSUE THREAD

**Issue by sunli829** [stjepang/async-dup#12]
It's a breaking change related to this [commit](https://github.com/smol-rs/async-dup/commit/50851bfd8e2e71a878dcafd2a04b4cdff565c236).

**Comment by taiki-e** [comment]
Thanks for the report, and sorry for the breakage! I've yanked 1.2.3.

Aside from that, in general, async codes that cause errors due to non-Send guards are wrong (especially if holding a guard alive across an `.await`) and can cause deadlocks.

**Comment by notgull** [comment]
There's no way to make `MutexGuard` on its own `Send` without unsafe code. I'm thinking about just pulling in `async-lock`, since with version 3.0 it now has a blocking mutex.
